// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void AttackEnemyHandler(ReducerEventContext ctx, ulong abilityId, ulong enemyId);
        public event AttackEnemyHandler? OnAttackEnemy;

        public void AttackEnemy(ulong abilityId, ulong enemyId)
        {
            conn.InternalCallReducer(new Reducer.AttackEnemy(abilityId, enemyId));
        }

        public bool InvokeAttackEnemy(ReducerEventContext ctx, Reducer.AttackEnemy args)
        {
            if (OnAttackEnemy == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnAttackEnemy(
                ctx,
                args.AbilityId,
                args.EnemyId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class AttackEnemy : Reducer, IReducerArgs
        {
            [DataMember(Name = "ability_id")]
            public ulong AbilityId;
            [DataMember(Name = "enemy_id")]
            public ulong EnemyId;

            public AttackEnemy(
                ulong AbilityId,
                ulong EnemyId
            )
            {
                this.AbilityId = AbilityId;
                this.EnemyId = EnemyId;
            }

            public AttackEnemy()
            {
            }

            string IReducerArgs.ReducerName => "attack_enemy";
        }
    }
}
