// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ChangeWeatherHandler(ReducerEventContext ctx, ulong zoneId, SpacetimeDB.Types.WeatherKind kind, float intensity);
        public event ChangeWeatherHandler? OnChangeWeather;

        public void ChangeWeather(ulong zoneId, SpacetimeDB.Types.WeatherKind kind, float intensity)
        {
            conn.InternalCallReducer(new Reducer.ChangeWeather(zoneId, kind, intensity));
        }

        public bool InvokeChangeWeather(ReducerEventContext ctx, Reducer.ChangeWeather args)
        {
            if (OnChangeWeather == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnChangeWeather(
                ctx,
                args.ZoneId,
                args.Kind,
                args.Intensity
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ChangeWeather : Reducer, IReducerArgs
        {
            [DataMember(Name = "zone_id")]
            public ulong ZoneId;
            [DataMember(Name = "kind")]
            public WeatherKind Kind;
            [DataMember(Name = "intensity")]
            public float Intensity;

            public ChangeWeather(
                ulong ZoneId,
                WeatherKind Kind,
                float Intensity
            )
            {
                this.ZoneId = ZoneId;
                this.Kind = Kind;
                this.Intensity = Intensity;
            }

            public ChangeWeather()
            {
            }

            string IReducerArgs.ReducerName => "change_weather";
        }
    }
}
