// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void CreateZoneHandler(ReducerEventContext ctx, string name, uint width, uint height);
        public event CreateZoneHandler? OnCreateZone;

        public void CreateZone(string name, uint width, uint height)
        {
            conn.InternalCallReducer(new Reducer.CreateZone(name, width, height));
        }

        public bool InvokeCreateZone(ReducerEventContext ctx, Reducer.CreateZone args)
        {
            if (OnCreateZone == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnCreateZone(
                ctx,
                args.Name,
                args.Width,
                args.Height
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class CreateZone : Reducer, IReducerArgs
        {
            [DataMember(Name = "name")]
            public string Name;
            [DataMember(Name = "width")]
            public uint Width;
            [DataMember(Name = "height")]
            public uint Height;

            public CreateZone(
                string Name,
                uint Width,
                uint Height
            )
            {
                this.Name = Name;
                this.Width = Width;
                this.Height = Height;
            }

            public CreateZone()
            {
                this.Name = "";
            }

            string IReducerArgs.ReducerName => "create_zone";
        }
    }
}
