// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void CreateSpawnPointHandler(ReducerEventContext ctx, ulong zoneId, float x, float y, ulong enemyDefId, uint maxCount, uint respawnDelayS);
        public event CreateSpawnPointHandler? OnCreateSpawnPoint;

        public void CreateSpawnPoint(ulong zoneId, float x, float y, ulong enemyDefId, uint maxCount, uint respawnDelayS)
        {
            conn.InternalCallReducer(new Reducer.CreateSpawnPoint(zoneId, x, y, enemyDefId, maxCount, respawnDelayS));
        }

        public bool InvokeCreateSpawnPoint(ReducerEventContext ctx, Reducer.CreateSpawnPoint args)
        {
            if (OnCreateSpawnPoint == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnCreateSpawnPoint(
                ctx,
                args.ZoneId,
                args.X,
                args.Y,
                args.EnemyDefId,
                args.MaxCount,
                args.RespawnDelayS
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class CreateSpawnPoint : Reducer, IReducerArgs
        {
            [DataMember(Name = "zone_id")]
            public ulong ZoneId;
            [DataMember(Name = "x")]
            public float X;
            [DataMember(Name = "y")]
            public float Y;
            [DataMember(Name = "enemy_def_id")]
            public ulong EnemyDefId;
            [DataMember(Name = "max_count")]
            public uint MaxCount;
            [DataMember(Name = "respawn_delay_s")]
            public uint RespawnDelayS;

            public CreateSpawnPoint(
                ulong ZoneId,
                float X,
                float Y,
                ulong EnemyDefId,
                uint MaxCount,
                uint RespawnDelayS
            )
            {
                this.ZoneId = ZoneId;
                this.X = X;
                this.Y = Y;
                this.EnemyDefId = EnemyDefId;
                this.MaxCount = MaxCount;
                this.RespawnDelayS = RespawnDelayS;
            }

            public CreateSpawnPoint()
            {
            }

            string IReducerArgs.ReducerName => "create_spawn_point";
        }
    }
}
