// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void CreateZoneHandler(ReducerEventContext ctx, string name, uint terrainWidth, uint terrainHeight, float waterLevel);
        public event CreateZoneHandler? OnCreateZone;

        public void CreateZone(string name, uint terrainWidth, uint terrainHeight, float waterLevel)
        {
            conn.InternalCallReducer(new Reducer.CreateZone(name, terrainWidth, terrainHeight, waterLevel));
        }

        public bool InvokeCreateZone(ReducerEventContext ctx, Reducer.CreateZone args)
        {
            if (OnCreateZone == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnCreateZone(
                ctx,
                args.Name,
                args.TerrainWidth,
                args.TerrainHeight,
                args.WaterLevel
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class CreateZone : Reducer, IReducerArgs
        {
            [DataMember(Name = "name")]
            public string Name;
            [DataMember(Name = "terrain_width")]
            public uint TerrainWidth;
            [DataMember(Name = "terrain_height")]
            public uint TerrainHeight;
            [DataMember(Name = "water_level")]
            public float WaterLevel;

            public CreateZone(
                string Name,
                uint TerrainWidth,
                uint TerrainHeight,
                float WaterLevel
            )
            {
                this.Name = Name;
                this.TerrainWidth = TerrainWidth;
                this.TerrainHeight = TerrainHeight;
                this.WaterLevel = WaterLevel;
            }

            public CreateZone()
            {
                this.Name = "";
            }

            string IReducerArgs.ReducerName => "create_zone";
        }
    }
}
