// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void CreatePortalHandler(ReducerEventContext ctx, ulong sourceZoneId, ulong destZoneId, float sourceX, float sourceY, float destSpawnX, float destSpawnY, bool bidirectional, string label);
        public event CreatePortalHandler? OnCreatePortal;

        public void CreatePortal(ulong sourceZoneId, ulong destZoneId, float sourceX, float sourceY, float destSpawnX, float destSpawnY, bool bidirectional, string label)
        {
            conn.InternalCallReducer(new Reducer.CreatePortal(sourceZoneId, destZoneId, sourceX, sourceY, destSpawnX, destSpawnY, bidirectional, label));
        }

        public bool InvokeCreatePortal(ReducerEventContext ctx, Reducer.CreatePortal args)
        {
            if (OnCreatePortal == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnCreatePortal(
                ctx,
                args.SourceZoneId,
                args.DestZoneId,
                args.SourceX,
                args.SourceY,
                args.DestSpawnX,
                args.DestSpawnY,
                args.Bidirectional,
                args.Label
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class CreatePortal : Reducer, IReducerArgs
        {
            [DataMember(Name = "source_zone_id")]
            public ulong SourceZoneId;
            [DataMember(Name = "dest_zone_id")]
            public ulong DestZoneId;
            [DataMember(Name = "source_x")]
            public float SourceX;
            [DataMember(Name = "source_y")]
            public float SourceY;
            [DataMember(Name = "dest_spawn_x")]
            public float DestSpawnX;
            [DataMember(Name = "dest_spawn_y")]
            public float DestSpawnY;
            [DataMember(Name = "bidirectional")]
            public bool Bidirectional;
            [DataMember(Name = "label")]
            public string Label;

            public CreatePortal(
                ulong SourceZoneId,
                ulong DestZoneId,
                float SourceX,
                float SourceY,
                float DestSpawnX,
                float DestSpawnY,
                bool Bidirectional,
                string Label
            )
            {
                this.SourceZoneId = SourceZoneId;
                this.DestZoneId = DestZoneId;
                this.SourceX = SourceX;
                this.SourceY = SourceY;
                this.DestSpawnX = DestSpawnX;
                this.DestSpawnY = DestSpawnY;
                this.Bidirectional = Bidirectional;
                this.Label = Label;
            }

            public CreatePortal()
            {
                this.Label = "";
            }

            string IReducerArgs.ReducerName => "create_portal";
        }
    }
}
