// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void CreateItemDefHandler(ReducerEventContext ctx, string name, string description, SpacetimeDB.Types.ItemType itemType, SpacetimeDB.Types.Rarity rarity, string iconName, int damageBonus, int armorBonus, int healing, uint value);
        public event CreateItemDefHandler? OnCreateItemDef;

        public void CreateItemDef(string name, string description, SpacetimeDB.Types.ItemType itemType, SpacetimeDB.Types.Rarity rarity, string iconName, int damageBonus, int armorBonus, int healing, uint value)
        {
            conn.InternalCallReducer(new Reducer.CreateItemDef(name, description, itemType, rarity, iconName, damageBonus, armorBonus, healing, value));
        }

        public bool InvokeCreateItemDef(ReducerEventContext ctx, Reducer.CreateItemDef args)
        {
            if (OnCreateItemDef == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnCreateItemDef(
                ctx,
                args.Name,
                args.Description,
                args.ItemType,
                args.Rarity,
                args.IconName,
                args.DamageBonus,
                args.ArmorBonus,
                args.Healing,
                args.Value
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class CreateItemDef : Reducer, IReducerArgs
        {
            [DataMember(Name = "name")]
            public string Name;
            [DataMember(Name = "description")]
            public string Description;
            [DataMember(Name = "item_type")]
            public ItemType ItemType;
            [DataMember(Name = "rarity")]
            public Rarity Rarity;
            [DataMember(Name = "icon_name")]
            public string IconName;
            [DataMember(Name = "damage_bonus")]
            public int DamageBonus;
            [DataMember(Name = "armor_bonus")]
            public int ArmorBonus;
            [DataMember(Name = "healing")]
            public int Healing;
            [DataMember(Name = "value")]
            public uint Value;

            public CreateItemDef(
                string Name,
                string Description,
                ItemType ItemType,
                Rarity Rarity,
                string IconName,
                int DamageBonus,
                int ArmorBonus,
                int Healing,
                uint Value
            )
            {
                this.Name = Name;
                this.Description = Description;
                this.ItemType = ItemType;
                this.Rarity = Rarity;
                this.IconName = IconName;
                this.DamageBonus = DamageBonus;
                this.ArmorBonus = ArmorBonus;
                this.Healing = Healing;
                this.Value = Value;
            }

            public CreateItemDef()
            {
                this.Name = "";
                this.Description = "";
                this.IconName = "";
            }

            string IReducerArgs.ReducerName => "create_item_def";
        }
    }
}
