// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void CreateLootTableHandler(ReducerEventContext ctx, ulong enemyDefId, ulong itemDefId, uint dropChance, uint minQuantity, uint maxQuantity);
        public event CreateLootTableHandler? OnCreateLootTable;

        public void CreateLootTable(ulong enemyDefId, ulong itemDefId, uint dropChance, uint minQuantity, uint maxQuantity)
        {
            conn.InternalCallReducer(new Reducer.CreateLootTable(enemyDefId, itemDefId, dropChance, minQuantity, maxQuantity));
        }

        public bool InvokeCreateLootTable(ReducerEventContext ctx, Reducer.CreateLootTable args)
        {
            if (OnCreateLootTable == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnCreateLootTable(
                ctx,
                args.EnemyDefId,
                args.ItemDefId,
                args.DropChance,
                args.MinQuantity,
                args.MaxQuantity
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class CreateLootTable : Reducer, IReducerArgs
        {
            [DataMember(Name = "enemy_def_id")]
            public ulong EnemyDefId;
            [DataMember(Name = "item_def_id")]
            public ulong ItemDefId;
            [DataMember(Name = "drop_chance")]
            public uint DropChance;
            [DataMember(Name = "min_quantity")]
            public uint MinQuantity;
            [DataMember(Name = "max_quantity")]
            public uint MaxQuantity;

            public CreateLootTable(
                ulong EnemyDefId,
                ulong ItemDefId,
                uint DropChance,
                uint MinQuantity,
                uint MaxQuantity
            )
            {
                this.EnemyDefId = EnemyDefId;
                this.ItemDefId = ItemDefId;
                this.DropChance = DropChance;
                this.MinQuantity = MinQuantity;
                this.MaxQuantity = MaxQuantity;
            }

            public CreateLootTable()
            {
            }

            string IReducerArgs.ReducerName => "create_loot_table";
        }
    }
}
