// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void CreateEnemyDefHandler(ReducerEventContext ctx, string name, SpacetimeDB.Types.EnemyType enemyType, string prefabName, int maxHealth, int damage, float aggroRange, float attackRange, ulong attackSpeedMs, float moveSpeed);
        public event CreateEnemyDefHandler? OnCreateEnemyDef;

        public void CreateEnemyDef(string name, SpacetimeDB.Types.EnemyType enemyType, string prefabName, int maxHealth, int damage, float aggroRange, float attackRange, ulong attackSpeedMs, float moveSpeed)
        {
            conn.InternalCallReducer(new Reducer.CreateEnemyDef(name, enemyType, prefabName, maxHealth, damage, aggroRange, attackRange, attackSpeedMs, moveSpeed));
        }

        public bool InvokeCreateEnemyDef(ReducerEventContext ctx, Reducer.CreateEnemyDef args)
        {
            if (OnCreateEnemyDef == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnCreateEnemyDef(
                ctx,
                args.Name,
                args.EnemyType,
                args.PrefabName,
                args.MaxHealth,
                args.Damage,
                args.AggroRange,
                args.AttackRange,
                args.AttackSpeedMs,
                args.MoveSpeed
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class CreateEnemyDef : Reducer, IReducerArgs
        {
            [DataMember(Name = "name")]
            public string Name;
            [DataMember(Name = "enemy_type")]
            public EnemyType EnemyType;
            [DataMember(Name = "prefab_name")]
            public string PrefabName;
            [DataMember(Name = "max_health")]
            public int MaxHealth;
            [DataMember(Name = "damage")]
            public int Damage;
            [DataMember(Name = "aggro_range")]
            public float AggroRange;
            [DataMember(Name = "attack_range")]
            public float AttackRange;
            [DataMember(Name = "attack_speed_ms")]
            public ulong AttackSpeedMs;
            [DataMember(Name = "move_speed")]
            public float MoveSpeed;

            public CreateEnemyDef(
                string Name,
                EnemyType EnemyType,
                string PrefabName,
                int MaxHealth,
                int Damage,
                float AggroRange,
                float AttackRange,
                ulong AttackSpeedMs,
                float MoveSpeed
            )
            {
                this.Name = Name;
                this.EnemyType = EnemyType;
                this.PrefabName = PrefabName;
                this.MaxHealth = MaxHealth;
                this.Damage = Damage;
                this.AggroRange = AggroRange;
                this.AttackRange = AttackRange;
                this.AttackSpeedMs = AttackSpeedMs;
                this.MoveSpeed = MoveSpeed;
            }

            public CreateEnemyDef()
            {
                this.Name = "";
                this.PrefabName = "";
            }

            string IReducerArgs.ReducerName => "create_enemy_def";
        }
    }
}
