// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void DeleteLootTableHandler(ReducerEventContext ctx, ulong lootTableId);
        public event DeleteLootTableHandler? OnDeleteLootTable;

        public void DeleteLootTable(ulong lootTableId)
        {
            conn.InternalCallReducer(new Reducer.DeleteLootTable(lootTableId));
        }

        public bool InvokeDeleteLootTable(ReducerEventContext ctx, Reducer.DeleteLootTable args)
        {
            if (OnDeleteLootTable == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnDeleteLootTable(
                ctx,
                args.LootTableId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class DeleteLootTable : Reducer, IReducerArgs
        {
            [DataMember(Name = "loot_table_id")]
            public ulong LootTableId;

            public DeleteLootTable(ulong LootTableId)
            {
                this.LootTableId = LootTableId;
            }

            public DeleteLootTable()
            {
            }

            string IReducerArgs.ReducerName => "delete_loot_table";
        }
    }
}
