// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void DeleteEnemyDefHandler(ReducerEventContext ctx, ulong defId);
        public event DeleteEnemyDefHandler? OnDeleteEnemyDef;

        public void DeleteEnemyDef(ulong defId)
        {
            conn.InternalCallReducer(new Reducer.DeleteEnemyDef(defId));
        }

        public bool InvokeDeleteEnemyDef(ReducerEventContext ctx, Reducer.DeleteEnemyDef args)
        {
            if (OnDeleteEnemyDef == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnDeleteEnemyDef(
                ctx,
                args.DefId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class DeleteEnemyDef : Reducer, IReducerArgs
        {
            [DataMember(Name = "def_id")]
            public ulong DefId;

            public DeleteEnemyDef(ulong DefId)
            {
                this.DefId = DefId;
            }

            public DeleteEnemyDef()
            {
            }

            string IReducerArgs.ReducerName => "delete_enemy_def";
        }
    }
}
