// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void DeleteSpawnPointHandler(ReducerEventContext ctx, ulong spId);
        public event DeleteSpawnPointHandler? OnDeleteSpawnPoint;

        public void DeleteSpawnPoint(ulong spId)
        {
            conn.InternalCallReducer(new Reducer.DeleteSpawnPoint(spId));
        }

        public bool InvokeDeleteSpawnPoint(ReducerEventContext ctx, Reducer.DeleteSpawnPoint args)
        {
            if (OnDeleteSpawnPoint == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnDeleteSpawnPoint(
                ctx,
                args.SpId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class DeleteSpawnPoint : Reducer, IReducerArgs
        {
            [DataMember(Name = "sp_id")]
            public ulong SpId;

            public DeleteSpawnPoint(ulong SpId)
            {
                this.SpId = SpId;
            }

            public DeleteSpawnPoint()
            {
            }

            string IReducerArgs.ReducerName => "delete_spawn_point";
        }
    }
}
