// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void DeleteItemDefHandler(ReducerEventContext ctx, ulong itemDefId);
        public event DeleteItemDefHandler? OnDeleteItemDef;

        public void DeleteItemDef(ulong itemDefId)
        {
            conn.InternalCallReducer(new Reducer.DeleteItemDef(itemDefId));
        }

        public bool InvokeDeleteItemDef(ReducerEventContext ctx, Reducer.DeleteItemDef args)
        {
            if (OnDeleteItemDef == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnDeleteItemDef(
                ctx,
                args.ItemDefId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class DeleteItemDef : Reducer, IReducerArgs
        {
            [DataMember(Name = "item_def_id")]
            public ulong ItemDefId;

            public DeleteItemDef(ulong ItemDefId)
            {
                this.ItemDefId = ItemDefId;
            }

            public DeleteItemDef()
            {
            }

            string IReducerArgs.ReducerName => "delete_item_def";
        }
    }
}
