// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void DeleteZoneHandler(ReducerEventContext ctx, ulong zoneId);
        public event DeleteZoneHandler? OnDeleteZone;

        public void DeleteZone(ulong zoneId)
        {
            conn.InternalCallReducer(new Reducer.DeleteZone(zoneId));
        }

        public bool InvokeDeleteZone(ReducerEventContext ctx, Reducer.DeleteZone args)
        {
            if (OnDeleteZone == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnDeleteZone(
                ctx,
                args.ZoneId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class DeleteZone : Reducer, IReducerArgs
        {
            [DataMember(Name = "zone_id")]
            public ulong ZoneId;

            public DeleteZone(ulong ZoneId)
            {
                this.ZoneId = ZoneId;
            }

            public DeleteZone()
            {
            }

            string IReducerArgs.ReducerName => "delete_zone";
        }
    }
}
