// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void GiveItemHandler(ReducerEventContext ctx, ulong playerId, ulong itemDefId, uint quantity);
        public event GiveItemHandler? OnGiveItem;

        public void GiveItem(ulong playerId, ulong itemDefId, uint quantity)
        {
            conn.InternalCallReducer(new Reducer.GiveItem(playerId, itemDefId, quantity));
        }

        public bool InvokeGiveItem(ReducerEventContext ctx, Reducer.GiveItem args)
        {
            if (OnGiveItem == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnGiveItem(
                ctx,
                args.PlayerId,
                args.ItemDefId,
                args.Quantity
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class GiveItem : Reducer, IReducerArgs
        {
            [DataMember(Name = "player_id")]
            public ulong PlayerId;
            [DataMember(Name = "item_def_id")]
            public ulong ItemDefId;
            [DataMember(Name = "quantity")]
            public uint Quantity;

            public GiveItem(
                ulong PlayerId,
                ulong ItemDefId,
                uint Quantity
            )
            {
                this.PlayerId = PlayerId;
                this.ItemDefId = ItemDefId;
                this.Quantity = Quantity;
            }

            public GiveItem()
            {
            }

            string IReducerArgs.ReducerName => "give_item";
        }
    }
}
