// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void MovePlayerHandler(ReducerEventContext ctx, float newX, float newY);
        public event MovePlayerHandler? OnMovePlayer;

        public void MovePlayer(float newX, float newY)
        {
            conn.InternalCallReducer(new Reducer.MovePlayer(newX, newY));
        }

        public bool InvokeMovePlayer(ReducerEventContext ctx, Reducer.MovePlayer args)
        {
            if (OnMovePlayer == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnMovePlayer(
                ctx,
                args.NewX,
                args.NewY
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class MovePlayer : Reducer, IReducerArgs
        {
            [DataMember(Name = "new_x")]
            public float NewX;
            [DataMember(Name = "new_y")]
            public float NewY;

            public MovePlayer(
                float NewX,
                float NewY
            )
            {
                this.NewX = NewX;
                this.NewY = NewY;
            }

            public MovePlayer()
            {
            }

            string IReducerArgs.ReducerName => "move_player";
        }
    }
}
