// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void PickupItemHandler(ReducerEventContext ctx, ulong itemDropId);
        public event PickupItemHandler? OnPickupItem;

        public void PickupItem(ulong itemDropId)
        {
            conn.InternalCallReducer(new Reducer.PickupItem(itemDropId));
        }

        public bool InvokePickupItem(ReducerEventContext ctx, Reducer.PickupItem args)
        {
            if (OnPickupItem == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnPickupItem(
                ctx,
                args.ItemDropId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class PickupItem : Reducer, IReducerArgs
        {
            [DataMember(Name = "item_drop_id")]
            public ulong ItemDropId;

            public PickupItem(ulong ItemDropId)
            {
                this.ItemDropId = ItemDropId;
            }

            public PickupItem()
            {
            }

            string IReducerArgs.ReducerName => "pickup_item";
        }
    }
}
