// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void SetZoneMoodHandler(ReducerEventContext ctx, ulong zoneId, uint moodPresetId);
        public event SetZoneMoodHandler? OnSetZoneMood;

        public void SetZoneMood(ulong zoneId, uint moodPresetId)
        {
            conn.InternalCallReducer(new Reducer.SetZoneMood(zoneId, moodPresetId));
        }

        public bool InvokeSetZoneMood(ReducerEventContext ctx, Reducer.SetZoneMood args)
        {
            if (OnSetZoneMood == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnSetZoneMood(
                ctx,
                args.ZoneId,
                args.MoodPresetId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class SetZoneMood : Reducer, IReducerArgs
        {
            [DataMember(Name = "zone_id")]
            public ulong ZoneId;
            [DataMember(Name = "mood_preset_id")]
            public uint MoodPresetId;

            public SetZoneMood(
                ulong ZoneId,
                uint MoodPresetId
            )
            {
                this.ZoneId = ZoneId;
                this.MoodPresetId = MoodPresetId;
            }

            public SetZoneMood()
            {
            }

            string IReducerArgs.ReducerName => "set_zone_mood";
        }
    }
}
