// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void SpawnEntityHandler(ReducerEventContext ctx, ulong zoneId, string prefabName, float x, float y, float elevation, string entityType);
        public event SpawnEntityHandler? OnSpawnEntity;

        public void SpawnEntity(ulong zoneId, string prefabName, float x, float y, float elevation, string entityType)
        {
            conn.InternalCallReducer(new Reducer.SpawnEntity(zoneId, prefabName, x, y, elevation, entityType));
        }

        public bool InvokeSpawnEntity(ReducerEventContext ctx, Reducer.SpawnEntity args)
        {
            if (OnSpawnEntity == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnSpawnEntity(
                ctx,
                args.ZoneId,
                args.PrefabName,
                args.X,
                args.Y,
                args.Elevation,
                args.EntityType
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class SpawnEntity : Reducer, IReducerArgs
        {
            [DataMember(Name = "zone_id")]
            public ulong ZoneId;
            [DataMember(Name = "prefab_name")]
            public string PrefabName;
            [DataMember(Name = "x")]
            public float X;
            [DataMember(Name = "y")]
            public float Y;
            [DataMember(Name = "elevation")]
            public float Elevation;
            [DataMember(Name = "entity_type")]
            public string EntityType;

            public SpawnEntity(
                ulong ZoneId,
                string PrefabName,
                float X,
                float Y,
                float Elevation,
                string EntityType
            )
            {
                this.ZoneId = ZoneId;
                this.PrefabName = PrefabName;
                this.X = X;
                this.Y = Y;
                this.Elevation = Elevation;
                this.EntityType = EntityType;
            }

            public SpawnEntity()
            {
                this.PrefabName = "";
                this.EntityType = "";
            }

            string IReducerArgs.ReducerName => "spawn_entity";
        }
    }
}
