// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void SpawnEnemyManualHandler(ReducerEventContext ctx, ulong zoneId, float x, float y, ulong enemyDefId);
        public event SpawnEnemyManualHandler? OnSpawnEnemyManual;

        public void SpawnEnemyManual(ulong zoneId, float x, float y, ulong enemyDefId)
        {
            conn.InternalCallReducer(new Reducer.SpawnEnemyManual(zoneId, x, y, enemyDefId));
        }

        public bool InvokeSpawnEnemyManual(ReducerEventContext ctx, Reducer.SpawnEnemyManual args)
        {
            if (OnSpawnEnemyManual == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnSpawnEnemyManual(
                ctx,
                args.ZoneId,
                args.X,
                args.Y,
                args.EnemyDefId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class SpawnEnemyManual : Reducer, IReducerArgs
        {
            [DataMember(Name = "zone_id")]
            public ulong ZoneId;
            [DataMember(Name = "x")]
            public float X;
            [DataMember(Name = "y")]
            public float Y;
            [DataMember(Name = "enemy_def_id")]
            public ulong EnemyDefId;

            public SpawnEnemyManual(
                ulong ZoneId,
                float X,
                float Y,
                ulong EnemyDefId
            )
            {
                this.ZoneId = ZoneId;
                this.X = X;
                this.Y = Y;
                this.EnemyDefId = EnemyDefId;
            }

            public SpawnEnemyManual()
            {
            }

            string IReducerArgs.ReducerName => "spawn_enemy_manual";
        }
    }
}
