// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void UpdateAiStateHandler(ReducerEventContext ctx, ulong enemyId, SpacetimeDB.Types.AiState newState, ulong? targetPlayerId);
        public event UpdateAiStateHandler? OnUpdateAiState;

        public void UpdateAiState(ulong enemyId, SpacetimeDB.Types.AiState newState, ulong? targetPlayerId)
        {
            conn.InternalCallReducer(new Reducer.UpdateAiState(enemyId, newState, targetPlayerId));
        }

        public bool InvokeUpdateAiState(ReducerEventContext ctx, Reducer.UpdateAiState args)
        {
            if (OnUpdateAiState == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnUpdateAiState(
                ctx,
                args.EnemyId,
                args.NewState,
                args.TargetPlayerId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class UpdateAiState : Reducer, IReducerArgs
        {
            [DataMember(Name = "enemy_id")]
            public ulong EnemyId;
            [DataMember(Name = "new_state")]
            public AiState NewState;
            [DataMember(Name = "target_player_id")]
            public ulong? TargetPlayerId;

            public UpdateAiState(
                ulong EnemyId,
                AiState NewState,
                ulong? TargetPlayerId
            )
            {
                this.EnemyId = EnemyId;
                this.NewState = NewState;
                this.TargetPlayerId = TargetPlayerId;
            }

            public UpdateAiState()
            {
            }

            string IReducerArgs.ReducerName => "update_ai_state";
        }
    }
}
