// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void UpdateTerrainChunkHandler(ReducerEventContext ctx, ulong zoneId, uint chunkX, uint chunkZ, System.Collections.Generic.List<byte> heightData, System.Collections.Generic.List<byte> splatData);
        public event UpdateTerrainChunkHandler? OnUpdateTerrainChunk;

        public void UpdateTerrainChunk(ulong zoneId, uint chunkX, uint chunkZ, System.Collections.Generic.List<byte> heightData, System.Collections.Generic.List<byte> splatData)
        {
            conn.InternalCallReducer(new Reducer.UpdateTerrainChunk(zoneId, chunkX, chunkZ, heightData, splatData));
        }

        public bool InvokeUpdateTerrainChunk(ReducerEventContext ctx, Reducer.UpdateTerrainChunk args)
        {
            if (OnUpdateTerrainChunk == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnUpdateTerrainChunk(
                ctx,
                args.ZoneId,
                args.ChunkX,
                args.ChunkZ,
                args.HeightData,
                args.SplatData
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class UpdateTerrainChunk : Reducer, IReducerArgs
        {
            [DataMember(Name = "zone_id")]
            public ulong ZoneId;
            [DataMember(Name = "chunk_x")]
            public uint ChunkX;
            [DataMember(Name = "chunk_z")]
            public uint ChunkZ;
            [DataMember(Name = "height_data")]
            public System.Collections.Generic.List<byte> HeightData;
            [DataMember(Name = "splat_data")]
            public System.Collections.Generic.List<byte> SplatData;

            public UpdateTerrainChunk(
                ulong ZoneId,
                uint ChunkX,
                uint ChunkZ,
                System.Collections.Generic.List<byte> HeightData,
                System.Collections.Generic.List<byte> SplatData
            )
            {
                this.ZoneId = ZoneId;
                this.ChunkX = ChunkX;
                this.ChunkZ = ChunkZ;
                this.HeightData = HeightData;
                this.SplatData = SplatData;
            }

            public UpdateTerrainChunk()
            {
                this.HeightData = new();
                this.SplatData = new();
            }

            string IReducerArgs.ReducerName => "update_terrain_chunk";
        }
    }
}
