// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Ability
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "name")]
        public string Name;
        [DataMember(Name = "damage")]
        public int Damage;
        [DataMember(Name = "cooldown_ms")]
        public ulong CooldownMs;
        [DataMember(Name = "mana_cost")]
        public int ManaCost;
        [DataMember(Name = "range")]
        public float Range;
        [DataMember(Name = "ability_type")]
        public AbilityType AbilityType;

        public Ability(
            ulong Id,
            string Name,
            int Damage,
            ulong CooldownMs,
            int ManaCost,
            float Range,
            AbilityType AbilityType
        )
        {
            this.Id = Id;
            this.Name = Name;
            this.Damage = Damage;
            this.CooldownMs = CooldownMs;
            this.ManaCost = ManaCost;
            this.Range = Range;
            this.AbilityType = AbilityType;
        }

        public Ability()
        {
            this.Name = "";
        }
    }
}
