// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class CombatLog
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "timestamp")]
        public SpacetimeDB.Timestamp Timestamp;
        [DataMember(Name = "attacker_id")]
        public ulong AttackerId;
        [DataMember(Name = "target_id")]
        public ulong TargetId;
        [DataMember(Name = "ability_id")]
        public ulong AbilityId;
        [DataMember(Name = "damage_dealt")]
        public int DamageDealt;
        [DataMember(Name = "overkill")]
        public int Overkill;
        [DataMember(Name = "attacker_is_enemy")]
        public bool AttackerIsEnemy;
        [DataMember(Name = "target_is_enemy")]
        public bool TargetIsEnemy;

        public CombatLog(
            ulong Id,
            SpacetimeDB.Timestamp Timestamp,
            ulong AttackerId,
            ulong TargetId,
            ulong AbilityId,
            int DamageDealt,
            int Overkill,
            bool AttackerIsEnemy,
            bool TargetIsEnemy
        )
        {
            this.Id = Id;
            this.Timestamp = Timestamp;
            this.AttackerId = AttackerId;
            this.TargetId = TargetId;
            this.AbilityId = AbilityId;
            this.DamageDealt = DamageDealt;
            this.Overkill = Overkill;
            this.AttackerIsEnemy = AttackerIsEnemy;
            this.TargetIsEnemy = TargetIsEnemy;
        }

        public CombatLog()
        {
        }
    }
}
