// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class EnemyDespawnTimer
    {
        [DataMember(Name = "scheduled_id")]
        public ulong ScheduledId;
        [DataMember(Name = "scheduled_at")]
        public SpacetimeDB.ScheduleAt ScheduledAt;
        [DataMember(Name = "enemy_id")]
        public ulong EnemyId;

        public EnemyDespawnTimer(
            ulong ScheduledId,
            SpacetimeDB.ScheduleAt ScheduledAt,
            ulong EnemyId
        )
        {
            this.ScheduledId = ScheduledId;
            this.ScheduledAt = ScheduledAt;
            this.EnemyId = EnemyId;
        }

        public EnemyDespawnTimer()
        {
            this.ScheduledAt = null!;
        }
    }
}
