// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class EnemyDefinition
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "name")]
        public string Name;
        [DataMember(Name = "enemy_type")]
        public EnemyType EnemyType;
        [DataMember(Name = "prefab_name")]
        public string PrefabName;
        [DataMember(Name = "max_health")]
        public int MaxHealth;
        [DataMember(Name = "damage")]
        public int Damage;
        [DataMember(Name = "aggro_range")]
        public float AggroRange;
        [DataMember(Name = "attack_range")]
        public float AttackRange;
        [DataMember(Name = "attack_speed_ms")]
        public ulong AttackSpeedMs;
        [DataMember(Name = "move_speed")]
        public float MoveSpeed;

        public EnemyDefinition(
            ulong Id,
            string Name,
            EnemyType EnemyType,
            string PrefabName,
            int MaxHealth,
            int Damage,
            float AggroRange,
            float AttackRange,
            ulong AttackSpeedMs,
            float MoveSpeed
        )
        {
            this.Id = Id;
            this.Name = Name;
            this.EnemyType = EnemyType;
            this.PrefabName = PrefabName;
            this.MaxHealth = MaxHealth;
            this.Damage = Damage;
            this.AggroRange = AggroRange;
            this.AttackRange = AttackRange;
            this.AttackSpeedMs = AttackSpeedMs;
            this.MoveSpeed = MoveSpeed;
        }

        public EnemyDefinition()
        {
            this.Name = "";
            this.PrefabName = "";
        }
    }
}
