// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Enemy
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "zone_id")]
        public ulong ZoneId;
        [DataMember(Name = "spawn_point_id")]
        public ulong? SpawnPointId;
        [DataMember(Name = "enemy_def_id")]
        public ulong EnemyDefId;
        [DataMember(Name = "position_x")]
        public float PositionX;
        [DataMember(Name = "position_y")]
        public float PositionY;
        [DataMember(Name = "home_x")]
        public float HomeX;
        [DataMember(Name = "home_y")]
        public float HomeY;
        [DataMember(Name = "health")]
        public int Health;
        [DataMember(Name = "ai_state")]
        public AiState AiState;
        [DataMember(Name = "target_player_id")]
        public ulong? TargetPlayerId;
        [DataMember(Name = "last_attack_us")]
        public ulong LastAttackUs;
        [DataMember(Name = "is_dead")]
        public bool IsDead;

        public Enemy(
            ulong Id,
            ulong ZoneId,
            ulong? SpawnPointId,
            ulong EnemyDefId,
            float PositionX,
            float PositionY,
            float HomeX,
            float HomeY,
            int Health,
            AiState AiState,
            ulong? TargetPlayerId,
            ulong LastAttackUs,
            bool IsDead
        )
        {
            this.Id = Id;
            this.ZoneId = ZoneId;
            this.SpawnPointId = SpawnPointId;
            this.EnemyDefId = EnemyDefId;
            this.PositionX = PositionX;
            this.PositionY = PositionY;
            this.HomeX = HomeX;
            this.HomeY = HomeY;
            this.Health = Health;
            this.AiState = AiState;
            this.TargetPlayerId = TargetPlayerId;
            this.LastAttackUs = LastAttackUs;
            this.IsDead = IsDead;
        }

        public Enemy()
        {
        }
    }
}
