// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class EntityInstance
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "zone_id")]
        public ulong ZoneId;
        [DataMember(Name = "prefab_name")]
        public string PrefabName;
        [DataMember(Name = "position_x")]
        public float PositionX;
        [DataMember(Name = "position_y")]
        public float PositionY;
        [DataMember(Name = "entity_type")]
        public string EntityType;

        public EntityInstance(
            ulong Id,
            ulong ZoneId,
            string PrefabName,
            float PositionX,
            float PositionY,
            string EntityType
        )
        {
            this.Id = Id;
            this.ZoneId = ZoneId;
            this.PrefabName = PrefabName;
            this.PositionX = PositionX;
            this.PositionY = PositionY;
            this.EntityType = EntityType;
        }

        public EntityInstance()
        {
            this.PrefabName = "";
            this.EntityType = "";
        }
    }
}
