// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Equipment
    {
        [DataMember(Name = "player_id")]
        public ulong PlayerId;
        [DataMember(Name = "weapon_id")]
        public ulong? WeaponId;
        [DataMember(Name = "armor_id")]
        public ulong? ArmorId;
        [DataMember(Name = "accessory_id")]
        public ulong? AccessoryId;

        public Equipment(
            ulong PlayerId,
            ulong? WeaponId,
            ulong? ArmorId,
            ulong? AccessoryId
        )
        {
            this.PlayerId = PlayerId;
            this.WeaponId = WeaponId;
            this.ArmorId = ArmorId;
            this.AccessoryId = AccessoryId;
        }

        public Equipment()
        {
        }
    }
}
