// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Inventory
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "player_id")]
        public ulong PlayerId;
        [DataMember(Name = "item_def_id")]
        public ulong ItemDefId;
        [DataMember(Name = "quantity")]
        public uint Quantity;

        public Inventory(
            ulong Id,
            ulong PlayerId,
            ulong ItemDefId,
            uint Quantity
        )
        {
            this.Id = Id;
            this.PlayerId = PlayerId;
            this.ItemDefId = ItemDefId;
            this.Quantity = Quantity;
        }

        public Inventory()
        {
        }
    }
}
