// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ItemDrop
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "zone_id")]
        public ulong ZoneId;
        [DataMember(Name = "item_def_id")]
        public ulong ItemDefId;
        [DataMember(Name = "quantity")]
        public uint Quantity;
        [DataMember(Name = "pos_x")]
        public float PosX;
        [DataMember(Name = "pos_y")]
        public float PosY;

        public ItemDrop(
            ulong Id,
            ulong ZoneId,
            ulong ItemDefId,
            uint Quantity,
            float PosX,
            float PosY
        )
        {
            this.Id = Id;
            this.ZoneId = ZoneId;
            this.ItemDefId = ItemDefId;
            this.Quantity = Quantity;
            this.PosX = PosX;
            this.PosY = PosY;
        }

        public ItemDrop()
        {
        }
    }
}
