// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ItemDefinition
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "name")]
        public string Name;
        [DataMember(Name = "description")]
        public string Description;
        [DataMember(Name = "item_type")]
        public ItemType ItemType;
        [DataMember(Name = "rarity")]
        public Rarity Rarity;
        [DataMember(Name = "icon_name")]
        public string IconName;
        [DataMember(Name = "damage_bonus")]
        public int DamageBonus;
        [DataMember(Name = "armor_bonus")]
        public int ArmorBonus;
        [DataMember(Name = "healing")]
        public int Healing;
        [DataMember(Name = "value")]
        public uint Value;

        public ItemDefinition(
            ulong Id,
            string Name,
            string Description,
            ItemType ItemType,
            Rarity Rarity,
            string IconName,
            int DamageBonus,
            int ArmorBonus,
            int Healing,
            uint Value
        )
        {
            this.Id = Id;
            this.Name = Name;
            this.Description = Description;
            this.ItemType = ItemType;
            this.Rarity = Rarity;
            this.IconName = IconName;
            this.DamageBonus = DamageBonus;
            this.ArmorBonus = ArmorBonus;
            this.Healing = Healing;
            this.Value = Value;
        }

        public ItemDefinition()
        {
            this.Name = "";
            this.Description = "";
            this.IconName = "";
        }
    }
}
