// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class LootTable
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "enemy_def_id")]
        public ulong EnemyDefId;
        [DataMember(Name = "item_def_id")]
        public ulong ItemDefId;
        [DataMember(Name = "drop_chance")]
        public uint DropChance;
        [DataMember(Name = "min_quantity")]
        public uint MinQuantity;
        [DataMember(Name = "max_quantity")]
        public uint MaxQuantity;

        public LootTable(
            ulong Id,
            ulong EnemyDefId,
            ulong ItemDefId,
            uint DropChance,
            uint MinQuantity,
            uint MaxQuantity
        )
        {
            this.Id = Id;
            this.EnemyDefId = EnemyDefId;
            this.ItemDefId = ItemDefId;
            this.DropChance = DropChance;
            this.MinQuantity = MinQuantity;
            this.MaxQuantity = MaxQuantity;
        }

        public LootTable()
        {
        }
    }
}
