// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Player
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "identity")]
        public SpacetimeDB.Identity Identity;
        [DataMember(Name = "name")]
        public string Name;
        [DataMember(Name = "zone_id")]
        public ulong ZoneId;
        [DataMember(Name = "position_x")]
        public float PositionX;
        [DataMember(Name = "position_y")]
        public float PositionY;
        [DataMember(Name = "health")]
        public int Health;
        [DataMember(Name = "max_health")]
        public int MaxHealth;

        public Player(
            ulong Id,
            SpacetimeDB.Identity Identity,
            string Name,
            ulong ZoneId,
            float PositionX,
            float PositionY,
            int Health,
            int MaxHealth
        )
        {
            this.Id = Id;
            this.Identity = Identity;
            this.Name = Name;
            this.ZoneId = ZoneId;
            this.PositionX = PositionX;
            this.PositionY = PositionY;
            this.Health = Health;
            this.MaxHealth = MaxHealth;
        }

        public Player()
        {
            this.Name = "";
        }
    }
}
