// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class PlayerCooldown
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "player_id")]
        public ulong PlayerId;
        [DataMember(Name = "ability_id")]
        public ulong AbilityId;
        [DataMember(Name = "ready_at")]
        public SpacetimeDB.Timestamp ReadyAt;

        public PlayerCooldown(
            ulong Id,
            ulong PlayerId,
            ulong AbilityId,
            SpacetimeDB.Timestamp ReadyAt
        )
        {
            this.Id = Id;
            this.PlayerId = PlayerId;
            this.AbilityId = AbilityId;
            this.ReadyAt = ReadyAt;
        }

        public PlayerCooldown()
        {
        }
    }
}
