// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Portal
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "source_zone_id")]
        public ulong SourceZoneId;
        [DataMember(Name = "dest_zone_id")]
        public ulong DestZoneId;
        [DataMember(Name = "source_x")]
        public float SourceX;
        [DataMember(Name = "source_y")]
        public float SourceY;
        [DataMember(Name = "dest_spawn_x")]
        public float DestSpawnX;
        [DataMember(Name = "dest_spawn_y")]
        public float DestSpawnY;
        [DataMember(Name = "bidirectional")]
        public bool Bidirectional;
        [DataMember(Name = "label")]
        public string Label;

        public Portal(
            ulong Id,
            ulong SourceZoneId,
            ulong DestZoneId,
            float SourceX,
            float SourceY,
            float DestSpawnX,
            float DestSpawnY,
            bool Bidirectional,
            string Label
        )
        {
            this.Id = Id;
            this.SourceZoneId = SourceZoneId;
            this.DestZoneId = DestZoneId;
            this.SourceX = SourceX;
            this.SourceY = SourceY;
            this.DestSpawnX = DestSpawnX;
            this.DestSpawnY = DestSpawnY;
            this.Bidirectional = Bidirectional;
            this.Label = Label;
        }

        public Portal()
        {
            this.Label = "";
        }
    }
}
