// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class SpawnPoint
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "zone_id")]
        public ulong ZoneId;
        [DataMember(Name = "x")]
        public float X;
        [DataMember(Name = "y")]
        public float Y;
        [DataMember(Name = "enemy_def_id")]
        public ulong EnemyDefId;
        [DataMember(Name = "max_count")]
        public uint MaxCount;
        [DataMember(Name = "respawn_delay_s")]
        public uint RespawnDelayS;

        public SpawnPoint(
            ulong Id,
            ulong ZoneId,
            float X,
            float Y,
            ulong EnemyDefId,
            uint MaxCount,
            uint RespawnDelayS
        )
        {
            this.Id = Id;
            this.ZoneId = ZoneId;
            this.X = X;
            this.Y = Y;
            this.EnemyDefId = EnemyDefId;
            this.MaxCount = MaxCount;
            this.RespawnDelayS = RespawnDelayS;
        }

        public SpawnPoint()
        {
        }
    }
}
