// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class StatusEffect
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "target_id")]
        public ulong TargetId;
        [DataMember(Name = "effect_type")]
        public StatusEffectType EffectType;
        [DataMember(Name = "expires_at")]
        public SpacetimeDB.Timestamp ExpiresAt;
        [DataMember(Name = "damage_per_tick")]
        public int DamagePerTick;

        public StatusEffect(
            ulong Id,
            ulong TargetId,
            StatusEffectType EffectType,
            SpacetimeDB.Timestamp ExpiresAt,
            int DamagePerTick
        )
        {
            this.Id = Id;
            this.TargetId = TargetId;
            this.EffectType = EffectType;
            this.ExpiresAt = ExpiresAt;
            this.DamagePerTick = DamagePerTick;
        }

        public StatusEffect()
        {
        }
    }
}
