// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class TerrainChunk
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "zone_id")]
        public ulong ZoneId;
        [DataMember(Name = "chunk_x")]
        public uint ChunkX;
        [DataMember(Name = "chunk_z")]
        public uint ChunkZ;
        [DataMember(Name = "height_data")]
        public System.Collections.Generic.List<byte> HeightData;
        [DataMember(Name = "splat_data")]
        public System.Collections.Generic.List<byte> SplatData;

        public TerrainChunk(
            ulong Id,
            ulong ZoneId,
            uint ChunkX,
            uint ChunkZ,
            System.Collections.Generic.List<byte> HeightData,
            System.Collections.Generic.List<byte> SplatData
        )
        {
            this.Id = Id;
            this.ZoneId = ZoneId;
            this.ChunkX = ChunkX;
            this.ChunkZ = ChunkZ;
            this.HeightData = HeightData;
            this.SplatData = SplatData;
        }

        public TerrainChunk()
        {
            this.HeightData = new();
            this.SplatData = new();
        }
    }
}
