// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class WeatherState
    {
        [DataMember(Name = "zone_id")]
        public ulong ZoneId;
        [DataMember(Name = "kind")]
        public WeatherKind Kind;
        [DataMember(Name = "intensity")]
        public float Intensity;
        [DataMember(Name = "started_at")]
        public SpacetimeDB.Timestamp StartedAt;

        public WeatherState(
            ulong ZoneId,
            WeatherKind Kind,
            float Intensity,
            SpacetimeDB.Timestamp StartedAt
        )
        {
            this.ZoneId = ZoneId;
            this.Kind = Kind;
            this.Intensity = Intensity;
            this.StartedAt = StartedAt;
        }

        public WeatherState()
        {
        }
    }
}
