// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class WorldClock
    {
        [DataMember(Name = "id")]
        public byte Id;
        [DataMember(Name = "minutes_of_day")]
        public ushort MinutesOfDay;
        [DataMember(Name = "last_tick")]
        public SpacetimeDB.Timestamp LastTick;

        public WorldClock(
            byte Id,
            ushort MinutesOfDay,
            SpacetimeDB.Timestamp LastTick
        )
        {
            this.Id = Id;
            this.MinutesOfDay = MinutesOfDay;
            this.LastTick = LastTick;
        }

        public WorldClock()
        {
        }
    }
}
