// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Zone
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "name")]
        public string Name;
        [DataMember(Name = "grid_width")]
        public uint GridWidth;
        [DataMember(Name = "grid_height")]
        public uint GridHeight;

        public Zone(
            ulong Id,
            string Name,
            uint GridWidth,
            uint GridHeight
        )
        {
            this.Id = Id;
            this.Name = Name;
            this.GridWidth = GridWidth;
            this.GridHeight = GridHeight;
        }

        public Zone()
        {
            this.Name = "";
        }
    }
}
