// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Zone
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "name")]
        public string Name;
        [DataMember(Name = "terrain_width")]
        public uint TerrainWidth;
        [DataMember(Name = "terrain_height")]
        public uint TerrainHeight;
        [DataMember(Name = "water_level")]
        public float WaterLevel;

        public Zone(
            ulong Id,
            string Name,
            uint TerrainWidth,
            uint TerrainHeight,
            float WaterLevel
        )
        {
            this.Id = Id;
            this.Name = Name;
            this.TerrainWidth = TerrainWidth;
            this.TerrainHeight = TerrainHeight;
            this.WaterLevel = WaterLevel;
        }

        public Zone()
        {
            this.Name = "";
        }
    }
}
