// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class AbilityHandle : RemoteTableHandle<EventContext, Ability>
        {
            protected override string RemoteTableName => "ability";

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(Ability row) => row.Id;

                public IdUniqueIndex(AbilityHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal AbilityHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(Ability row) => row.Id;
        }

        public readonly AbilityHandle Ability;
    }

    public sealed class AbilityCols
    {
        public global::SpacetimeDB.Col<Ability, ulong> Id { get; }
        public global::SpacetimeDB.Col<Ability, string> Name { get; }
        public global::SpacetimeDB.Col<Ability, int> Damage { get; }
        public global::SpacetimeDB.Col<Ability, ulong> CooldownMs { get; }
        public global::SpacetimeDB.Col<Ability, int> ManaCost { get; }
        public global::SpacetimeDB.Col<Ability, float> Range { get; }
        public global::SpacetimeDB.Col<Ability, AbilityType> AbilityType { get; }

        public AbilityCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<Ability, ulong>(tableName, "id");
            Name = new global::SpacetimeDB.Col<Ability, string>(tableName, "name");
            Damage = new global::SpacetimeDB.Col<Ability, int>(tableName, "damage");
            CooldownMs = new global::SpacetimeDB.Col<Ability, ulong>(tableName, "cooldown_ms");
            ManaCost = new global::SpacetimeDB.Col<Ability, int>(tableName, "mana_cost");
            Range = new global::SpacetimeDB.Col<Ability, float>(tableName, "range");
            AbilityType = new global::SpacetimeDB.Col<Ability, AbilityType>(tableName, "ability_type");
        }
    }

    public sealed class AbilityIxCols
    {
        public global::SpacetimeDB.IxCol<Ability, ulong> Id { get; }

        public AbilityIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<Ability, ulong>(tableName, "id");
        }
    }
}
