// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class CombatLogHandle : RemoteTableHandle<EventContext, CombatLog>
        {
            protected override string RemoteTableName => "combat_log";

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(CombatLog row) => row.Id;

                public IdUniqueIndex(CombatLogHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal CombatLogHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(CombatLog row) => row.Id;
        }

        public readonly CombatLogHandle CombatLog;
    }

    public sealed class CombatLogCols
    {
        public global::SpacetimeDB.Col<CombatLog, ulong> Id { get; }
        public global::SpacetimeDB.Col<CombatLog, SpacetimeDB.Timestamp> Timestamp { get; }
        public global::SpacetimeDB.Col<CombatLog, ulong> AttackerId { get; }
        public global::SpacetimeDB.Col<CombatLog, ulong> TargetId { get; }
        public global::SpacetimeDB.Col<CombatLog, ulong> AbilityId { get; }
        public global::SpacetimeDB.Col<CombatLog, int> DamageDealt { get; }
        public global::SpacetimeDB.Col<CombatLog, int> Overkill { get; }
        public global::SpacetimeDB.Col<CombatLog, bool> AttackerIsEnemy { get; }
        public global::SpacetimeDB.Col<CombatLog, bool> TargetIsEnemy { get; }

        public CombatLogCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<CombatLog, ulong>(tableName, "id");
            Timestamp = new global::SpacetimeDB.Col<CombatLog, SpacetimeDB.Timestamp>(tableName, "timestamp");
            AttackerId = new global::SpacetimeDB.Col<CombatLog, ulong>(tableName, "attacker_id");
            TargetId = new global::SpacetimeDB.Col<CombatLog, ulong>(tableName, "target_id");
            AbilityId = new global::SpacetimeDB.Col<CombatLog, ulong>(tableName, "ability_id");
            DamageDealt = new global::SpacetimeDB.Col<CombatLog, int>(tableName, "damage_dealt");
            Overkill = new global::SpacetimeDB.Col<CombatLog, int>(tableName, "overkill");
            AttackerIsEnemy = new global::SpacetimeDB.Col<CombatLog, bool>(tableName, "attacker_is_enemy");
            TargetIsEnemy = new global::SpacetimeDB.Col<CombatLog, bool>(tableName, "target_is_enemy");
        }
    }

    public sealed class CombatLogIxCols
    {
        public global::SpacetimeDB.IxCol<CombatLog, ulong> Id { get; }

        public CombatLogIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<CombatLog, ulong>(tableName, "id");
        }
    }
}
