// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class EnemyDefHandle : RemoteTableHandle<EventContext, EnemyDefinition>
        {
            protected override string RemoteTableName => "enemy_def";

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(EnemyDefinition row) => row.Id;

                public IdUniqueIndex(EnemyDefHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal EnemyDefHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(EnemyDefinition row) => row.Id;
        }

        public readonly EnemyDefHandle EnemyDef;
    }

    public sealed class EnemyDefCols
    {
        public global::SpacetimeDB.Col<EnemyDefinition, ulong> Id { get; }
        public global::SpacetimeDB.Col<EnemyDefinition, string> Name { get; }
        public global::SpacetimeDB.Col<EnemyDefinition, EnemyType> EnemyType { get; }
        public global::SpacetimeDB.Col<EnemyDefinition, string> PrefabName { get; }
        public global::SpacetimeDB.Col<EnemyDefinition, int> MaxHealth { get; }
        public global::SpacetimeDB.Col<EnemyDefinition, int> Damage { get; }
        public global::SpacetimeDB.Col<EnemyDefinition, float> AggroRange { get; }
        public global::SpacetimeDB.Col<EnemyDefinition, float> AttackRange { get; }
        public global::SpacetimeDB.Col<EnemyDefinition, ulong> AttackSpeedMs { get; }
        public global::SpacetimeDB.Col<EnemyDefinition, float> MoveSpeed { get; }

        public EnemyDefCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<EnemyDefinition, ulong>(tableName, "id");
            Name = new global::SpacetimeDB.Col<EnemyDefinition, string>(tableName, "name");
            EnemyType = new global::SpacetimeDB.Col<EnemyDefinition, EnemyType>(tableName, "enemy_type");
            PrefabName = new global::SpacetimeDB.Col<EnemyDefinition, string>(tableName, "prefab_name");
            MaxHealth = new global::SpacetimeDB.Col<EnemyDefinition, int>(tableName, "max_health");
            Damage = new global::SpacetimeDB.Col<EnemyDefinition, int>(tableName, "damage");
            AggroRange = new global::SpacetimeDB.Col<EnemyDefinition, float>(tableName, "aggro_range");
            AttackRange = new global::SpacetimeDB.Col<EnemyDefinition, float>(tableName, "attack_range");
            AttackSpeedMs = new global::SpacetimeDB.Col<EnemyDefinition, ulong>(tableName, "attack_speed_ms");
            MoveSpeed = new global::SpacetimeDB.Col<EnemyDefinition, float>(tableName, "move_speed");
        }
    }

    public sealed class EnemyDefIxCols
    {
        public global::SpacetimeDB.IxCol<EnemyDefinition, ulong> Id { get; }

        public EnemyDefIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<EnemyDefinition, ulong>(tableName, "id");
        }
    }
}
