// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class EnemyHandle : RemoteTableHandle<EventContext, Enemy>
        {
            protected override string RemoteTableName => "enemy";

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(Enemy row) => row.Id;

                public IdUniqueIndex(EnemyHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            public sealed class ZoneIdIndex : BTreeIndexBase<ulong>
            {
                protected override ulong GetKey(Enemy row) => row.ZoneId;

                public ZoneIdIndex(EnemyHandle table) : base(table) { }
            }

            public readonly ZoneIdIndex ZoneId;

            internal EnemyHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
                ZoneId = new(this);
            }

            protected override object GetPrimaryKey(Enemy row) => row.Id;
        }

        public readonly EnemyHandle Enemy;
    }

    public sealed class EnemyCols
    {
        public global::SpacetimeDB.Col<Enemy, ulong> Id { get; }
        public global::SpacetimeDB.Col<Enemy, ulong> ZoneId { get; }
        public global::SpacetimeDB.NullableCol<Enemy, ulong> SpawnPointId { get; }
        public global::SpacetimeDB.Col<Enemy, ulong> EnemyDefId { get; }
        public global::SpacetimeDB.Col<Enemy, float> PositionX { get; }
        public global::SpacetimeDB.Col<Enemy, float> PositionY { get; }
        public global::SpacetimeDB.Col<Enemy, float> HomeX { get; }
        public global::SpacetimeDB.Col<Enemy, float> HomeY { get; }
        public global::SpacetimeDB.Col<Enemy, int> Health { get; }
        public global::SpacetimeDB.Col<Enemy, AiState> AiState { get; }
        public global::SpacetimeDB.NullableCol<Enemy, ulong> TargetPlayerId { get; }
        public global::SpacetimeDB.Col<Enemy, ulong> LastAttackUs { get; }
        public global::SpacetimeDB.Col<Enemy, bool> IsDead { get; }

        public EnemyCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<Enemy, ulong>(tableName, "id");
            ZoneId = new global::SpacetimeDB.Col<Enemy, ulong>(tableName, "zone_id");
            SpawnPointId = new global::SpacetimeDB.NullableCol<Enemy, ulong>(tableName, "spawn_point_id");
            EnemyDefId = new global::SpacetimeDB.Col<Enemy, ulong>(tableName, "enemy_def_id");
            PositionX = new global::SpacetimeDB.Col<Enemy, float>(tableName, "position_x");
            PositionY = new global::SpacetimeDB.Col<Enemy, float>(tableName, "position_y");
            HomeX = new global::SpacetimeDB.Col<Enemy, float>(tableName, "home_x");
            HomeY = new global::SpacetimeDB.Col<Enemy, float>(tableName, "home_y");
            Health = new global::SpacetimeDB.Col<Enemy, int>(tableName, "health");
            AiState = new global::SpacetimeDB.Col<Enemy, AiState>(tableName, "ai_state");
            TargetPlayerId = new global::SpacetimeDB.NullableCol<Enemy, ulong>(tableName, "target_player_id");
            LastAttackUs = new global::SpacetimeDB.Col<Enemy, ulong>(tableName, "last_attack_us");
            IsDead = new global::SpacetimeDB.Col<Enemy, bool>(tableName, "is_dead");
        }
    }

    public sealed class EnemyIxCols
    {
        public global::SpacetimeDB.IxCol<Enemy, ulong> Id { get; }
        public global::SpacetimeDB.IxCol<Enemy, ulong> ZoneId { get; }

        public EnemyIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<Enemy, ulong>(tableName, "id");
            ZoneId = new global::SpacetimeDB.IxCol<Enemy, ulong>(tableName, "zone_id");
        }
    }
}
