// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class EntityInstanceHandle : RemoteTableHandle<EventContext, EntityInstance>
        {
            protected override string RemoteTableName => "entity_instance";

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(EntityInstance row) => row.Id;

                public IdUniqueIndex(EntityInstanceHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal EntityInstanceHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(EntityInstance row) => row.Id;
        }

        public readonly EntityInstanceHandle EntityInstance;
    }

    public sealed class EntityInstanceCols
    {
        public global::SpacetimeDB.Col<EntityInstance, ulong> Id { get; }
        public global::SpacetimeDB.Col<EntityInstance, ulong> ZoneId { get; }
        public global::SpacetimeDB.Col<EntityInstance, string> PrefabName { get; }
        public global::SpacetimeDB.Col<EntityInstance, float> PositionX { get; }
        public global::SpacetimeDB.Col<EntityInstance, float> PositionY { get; }
        public global::SpacetimeDB.Col<EntityInstance, float> Elevation { get; }
        public global::SpacetimeDB.Col<EntityInstance, string> EntityType { get; }

        public EntityInstanceCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<EntityInstance, ulong>(tableName, "id");
            ZoneId = new global::SpacetimeDB.Col<EntityInstance, ulong>(tableName, "zone_id");
            PrefabName = new global::SpacetimeDB.Col<EntityInstance, string>(tableName, "prefab_name");
            PositionX = new global::SpacetimeDB.Col<EntityInstance, float>(tableName, "position_x");
            PositionY = new global::SpacetimeDB.Col<EntityInstance, float>(tableName, "position_y");
            Elevation = new global::SpacetimeDB.Col<EntityInstance, float>(tableName, "elevation");
            EntityType = new global::SpacetimeDB.Col<EntityInstance, string>(tableName, "entity_type");
        }
    }

    public sealed class EntityInstanceIxCols
    {
        public global::SpacetimeDB.IxCol<EntityInstance, ulong> Id { get; }

        public EntityInstanceIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<EntityInstance, ulong>(tableName, "id");
        }
    }
}
