// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class EquipmentHandle : RemoteTableHandle<EventContext, Equipment>
        {
            protected override string RemoteTableName => "equipment";

            public sealed class PlayerIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(Equipment row) => row.PlayerId;

                public PlayerIdUniqueIndex(EquipmentHandle table) : base(table) { }
            }

            public readonly PlayerIdUniqueIndex PlayerId;

            internal EquipmentHandle(DbConnection conn) : base(conn)
            {
                PlayerId = new(this);
            }

            protected override object GetPrimaryKey(Equipment row) => row.PlayerId;
        }

        public readonly EquipmentHandle Equipment;
    }

    public sealed class EquipmentCols
    {
        public global::SpacetimeDB.Col<Equipment, ulong> PlayerId { get; }
        public global::SpacetimeDB.NullableCol<Equipment, ulong> WeaponId { get; }
        public global::SpacetimeDB.NullableCol<Equipment, ulong> ArmorId { get; }
        public global::SpacetimeDB.NullableCol<Equipment, ulong> AccessoryId { get; }

        public EquipmentCols(string tableName)
        {
            PlayerId = new global::SpacetimeDB.Col<Equipment, ulong>(tableName, "player_id");
            WeaponId = new global::SpacetimeDB.NullableCol<Equipment, ulong>(tableName, "weapon_id");
            ArmorId = new global::SpacetimeDB.NullableCol<Equipment, ulong>(tableName, "armor_id");
            AccessoryId = new global::SpacetimeDB.NullableCol<Equipment, ulong>(tableName, "accessory_id");
        }
    }

    public sealed class EquipmentIxCols
    {
        public global::SpacetimeDB.IxCol<Equipment, ulong> PlayerId { get; }

        public EquipmentIxCols(string tableName)
        {
            PlayerId = new global::SpacetimeDB.IxCol<Equipment, ulong>(tableName, "player_id");
        }
    }
}
