// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class InventoryHandle : RemoteTableHandle<EventContext, Inventory>
        {
            protected override string RemoteTableName => "inventory";

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(Inventory row) => row.Id;

                public IdUniqueIndex(InventoryHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            public sealed class PlayerIdIndex : BTreeIndexBase<ulong>
            {
                protected override ulong GetKey(Inventory row) => row.PlayerId;

                public PlayerIdIndex(InventoryHandle table) : base(table) { }
            }

            public readonly PlayerIdIndex PlayerId;

            internal InventoryHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
                PlayerId = new(this);
            }

            protected override object GetPrimaryKey(Inventory row) => row.Id;
        }

        public readonly InventoryHandle Inventory;
    }

    public sealed class InventoryCols
    {
        public global::SpacetimeDB.Col<Inventory, ulong> Id { get; }
        public global::SpacetimeDB.Col<Inventory, ulong> PlayerId { get; }
        public global::SpacetimeDB.Col<Inventory, ulong> ItemDefId { get; }
        public global::SpacetimeDB.Col<Inventory, uint> Quantity { get; }

        public InventoryCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<Inventory, ulong>(tableName, "id");
            PlayerId = new global::SpacetimeDB.Col<Inventory, ulong>(tableName, "player_id");
            ItemDefId = new global::SpacetimeDB.Col<Inventory, ulong>(tableName, "item_def_id");
            Quantity = new global::SpacetimeDB.Col<Inventory, uint>(tableName, "quantity");
        }
    }

    public sealed class InventoryIxCols
    {
        public global::SpacetimeDB.IxCol<Inventory, ulong> Id { get; }
        public global::SpacetimeDB.IxCol<Inventory, ulong> PlayerId { get; }

        public InventoryIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<Inventory, ulong>(tableName, "id");
            PlayerId = new global::SpacetimeDB.IxCol<Inventory, ulong>(tableName, "player_id");
        }
    }
}
