// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class ItemDefHandle : RemoteTableHandle<EventContext, ItemDefinition>
        {
            protected override string RemoteTableName => "item_def";

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(ItemDefinition row) => row.Id;

                public IdUniqueIndex(ItemDefHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal ItemDefHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(ItemDefinition row) => row.Id;
        }

        public readonly ItemDefHandle ItemDef;
    }

    public sealed class ItemDefCols
    {
        public global::SpacetimeDB.Col<ItemDefinition, ulong> Id { get; }
        public global::SpacetimeDB.Col<ItemDefinition, string> Name { get; }
        public global::SpacetimeDB.Col<ItemDefinition, string> Description { get; }
        public global::SpacetimeDB.Col<ItemDefinition, ItemType> ItemType { get; }
        public global::SpacetimeDB.Col<ItemDefinition, Rarity> Rarity { get; }
        public global::SpacetimeDB.Col<ItemDefinition, string> IconName { get; }
        public global::SpacetimeDB.Col<ItemDefinition, int> DamageBonus { get; }
        public global::SpacetimeDB.Col<ItemDefinition, int> ArmorBonus { get; }
        public global::SpacetimeDB.Col<ItemDefinition, int> Healing { get; }
        public global::SpacetimeDB.Col<ItemDefinition, uint> Value { get; }

        public ItemDefCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<ItemDefinition, ulong>(tableName, "id");
            Name = new global::SpacetimeDB.Col<ItemDefinition, string>(tableName, "name");
            Description = new global::SpacetimeDB.Col<ItemDefinition, string>(tableName, "description");
            ItemType = new global::SpacetimeDB.Col<ItemDefinition, ItemType>(tableName, "item_type");
            Rarity = new global::SpacetimeDB.Col<ItemDefinition, Rarity>(tableName, "rarity");
            IconName = new global::SpacetimeDB.Col<ItemDefinition, string>(tableName, "icon_name");
            DamageBonus = new global::SpacetimeDB.Col<ItemDefinition, int>(tableName, "damage_bonus");
            ArmorBonus = new global::SpacetimeDB.Col<ItemDefinition, int>(tableName, "armor_bonus");
            Healing = new global::SpacetimeDB.Col<ItemDefinition, int>(tableName, "healing");
            Value = new global::SpacetimeDB.Col<ItemDefinition, uint>(tableName, "value");
        }
    }

    public sealed class ItemDefIxCols
    {
        public global::SpacetimeDB.IxCol<ItemDefinition, ulong> Id { get; }

        public ItemDefIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<ItemDefinition, ulong>(tableName, "id");
        }
    }
}
