// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class ItemDropHandle : RemoteTableHandle<EventContext, ItemDrop>
        {
            protected override string RemoteTableName => "item_drop";

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(ItemDrop row) => row.Id;

                public IdUniqueIndex(ItemDropHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            public sealed class ZoneIdIndex : BTreeIndexBase<ulong>
            {
                protected override ulong GetKey(ItemDrop row) => row.ZoneId;

                public ZoneIdIndex(ItemDropHandle table) : base(table) { }
            }

            public readonly ZoneIdIndex ZoneId;

            internal ItemDropHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
                ZoneId = new(this);
            }

            protected override object GetPrimaryKey(ItemDrop row) => row.Id;
        }

        public readonly ItemDropHandle ItemDrop;
    }

    public sealed class ItemDropCols
    {
        public global::SpacetimeDB.Col<ItemDrop, ulong> Id { get; }
        public global::SpacetimeDB.Col<ItemDrop, ulong> ZoneId { get; }
        public global::SpacetimeDB.Col<ItemDrop, ulong> ItemDefId { get; }
        public global::SpacetimeDB.Col<ItemDrop, uint> Quantity { get; }
        public global::SpacetimeDB.Col<ItemDrop, float> PosX { get; }
        public global::SpacetimeDB.Col<ItemDrop, float> PosY { get; }

        public ItemDropCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<ItemDrop, ulong>(tableName, "id");
            ZoneId = new global::SpacetimeDB.Col<ItemDrop, ulong>(tableName, "zone_id");
            ItemDefId = new global::SpacetimeDB.Col<ItemDrop, ulong>(tableName, "item_def_id");
            Quantity = new global::SpacetimeDB.Col<ItemDrop, uint>(tableName, "quantity");
            PosX = new global::SpacetimeDB.Col<ItemDrop, float>(tableName, "pos_x");
            PosY = new global::SpacetimeDB.Col<ItemDrop, float>(tableName, "pos_y");
        }
    }

    public sealed class ItemDropIxCols
    {
        public global::SpacetimeDB.IxCol<ItemDrop, ulong> Id { get; }
        public global::SpacetimeDB.IxCol<ItemDrop, ulong> ZoneId { get; }

        public ItemDropIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<ItemDrop, ulong>(tableName, "id");
            ZoneId = new global::SpacetimeDB.IxCol<ItemDrop, ulong>(tableName, "zone_id");
        }
    }
}
