// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class LootTableHandle : RemoteTableHandle<EventContext, LootTable>
        {
            protected override string RemoteTableName => "loot_table";

            public sealed class EnemyDefIdIndex : BTreeIndexBase<ulong>
            {
                protected override ulong GetKey(LootTable row) => row.EnemyDefId;

                public EnemyDefIdIndex(LootTableHandle table) : base(table) { }
            }

            public readonly EnemyDefIdIndex EnemyDefId;

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(LootTable row) => row.Id;

                public IdUniqueIndex(LootTableHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal LootTableHandle(DbConnection conn) : base(conn)
            {
                EnemyDefId = new(this);
                Id = new(this);
            }

            protected override object GetPrimaryKey(LootTable row) => row.Id;
        }

        public readonly LootTableHandle LootTable;
    }

    public sealed class LootTableCols
    {
        public global::SpacetimeDB.Col<LootTable, ulong> Id { get; }
        public global::SpacetimeDB.Col<LootTable, ulong> EnemyDefId { get; }
        public global::SpacetimeDB.Col<LootTable, ulong> ItemDefId { get; }
        public global::SpacetimeDB.Col<LootTable, uint> DropChance { get; }
        public global::SpacetimeDB.Col<LootTable, uint> MinQuantity { get; }
        public global::SpacetimeDB.Col<LootTable, uint> MaxQuantity { get; }

        public LootTableCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<LootTable, ulong>(tableName, "id");
            EnemyDefId = new global::SpacetimeDB.Col<LootTable, ulong>(tableName, "enemy_def_id");
            ItemDefId = new global::SpacetimeDB.Col<LootTable, ulong>(tableName, "item_def_id");
            DropChance = new global::SpacetimeDB.Col<LootTable, uint>(tableName, "drop_chance");
            MinQuantity = new global::SpacetimeDB.Col<LootTable, uint>(tableName, "min_quantity");
            MaxQuantity = new global::SpacetimeDB.Col<LootTable, uint>(tableName, "max_quantity");
        }
    }

    public sealed class LootTableIxCols
    {
        public global::SpacetimeDB.IxCol<LootTable, ulong> Id { get; }
        public global::SpacetimeDB.IxCol<LootTable, ulong> EnemyDefId { get; }

        public LootTableIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<LootTable, ulong>(tableName, "id");
            EnemyDefId = new global::SpacetimeDB.IxCol<LootTable, ulong>(tableName, "enemy_def_id");
        }
    }
}
