// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class PlayerCooldownHandle : RemoteTableHandle<EventContext, PlayerCooldown>
        {
            protected override string RemoteTableName => "player_cooldown";

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(PlayerCooldown row) => row.Id;

                public IdUniqueIndex(PlayerCooldownHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            public sealed class PlayerIdIndex : BTreeIndexBase<ulong>
            {
                protected override ulong GetKey(PlayerCooldown row) => row.PlayerId;

                public PlayerIdIndex(PlayerCooldownHandle table) : base(table) { }
            }

            public readonly PlayerIdIndex PlayerId;

            internal PlayerCooldownHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
                PlayerId = new(this);
            }

            protected override object GetPrimaryKey(PlayerCooldown row) => row.Id;
        }

        public readonly PlayerCooldownHandle PlayerCooldown;
    }

    public sealed class PlayerCooldownCols
    {
        public global::SpacetimeDB.Col<PlayerCooldown, ulong> Id { get; }
        public global::SpacetimeDB.Col<PlayerCooldown, ulong> PlayerId { get; }
        public global::SpacetimeDB.Col<PlayerCooldown, ulong> AbilityId { get; }
        public global::SpacetimeDB.Col<PlayerCooldown, SpacetimeDB.Timestamp> ReadyAt { get; }

        public PlayerCooldownCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<PlayerCooldown, ulong>(tableName, "id");
            PlayerId = new global::SpacetimeDB.Col<PlayerCooldown, ulong>(tableName, "player_id");
            AbilityId = new global::SpacetimeDB.Col<PlayerCooldown, ulong>(tableName, "ability_id");
            ReadyAt = new global::SpacetimeDB.Col<PlayerCooldown, SpacetimeDB.Timestamp>(tableName, "ready_at");
        }
    }

    public sealed class PlayerCooldownIxCols
    {
        public global::SpacetimeDB.IxCol<PlayerCooldown, ulong> Id { get; }
        public global::SpacetimeDB.IxCol<PlayerCooldown, ulong> PlayerId { get; }

        public PlayerCooldownIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<PlayerCooldown, ulong>(tableName, "id");
            PlayerId = new global::SpacetimeDB.IxCol<PlayerCooldown, ulong>(tableName, "player_id");
        }
    }
}
