// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class PortalHandle : RemoteTableHandle<EventContext, Portal>
        {
            protected override string RemoteTableName => "portal";

            public sealed class DestZoneIdIndex : BTreeIndexBase<ulong>
            {
                protected override ulong GetKey(Portal row) => row.DestZoneId;

                public DestZoneIdIndex(PortalHandle table) : base(table) { }
            }

            public readonly DestZoneIdIndex DestZoneId;

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(Portal row) => row.Id;

                public IdUniqueIndex(PortalHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            public sealed class SourceZoneIdIndex : BTreeIndexBase<ulong>
            {
                protected override ulong GetKey(Portal row) => row.SourceZoneId;

                public SourceZoneIdIndex(PortalHandle table) : base(table) { }
            }

            public readonly SourceZoneIdIndex SourceZoneId;

            internal PortalHandle(DbConnection conn) : base(conn)
            {
                DestZoneId = new(this);
                Id = new(this);
                SourceZoneId = new(this);
            }

            protected override object GetPrimaryKey(Portal row) => row.Id;
        }

        public readonly PortalHandle Portal;
    }

    public sealed class PortalCols
    {
        public global::SpacetimeDB.Col<Portal, ulong> Id { get; }
        public global::SpacetimeDB.Col<Portal, ulong> SourceZoneId { get; }
        public global::SpacetimeDB.Col<Portal, ulong> DestZoneId { get; }
        public global::SpacetimeDB.Col<Portal, float> SourceX { get; }
        public global::SpacetimeDB.Col<Portal, float> SourceY { get; }
        public global::SpacetimeDB.Col<Portal, float> DestSpawnX { get; }
        public global::SpacetimeDB.Col<Portal, float> DestSpawnY { get; }
        public global::SpacetimeDB.Col<Portal, bool> Bidirectional { get; }
        public global::SpacetimeDB.Col<Portal, string> Label { get; }

        public PortalCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<Portal, ulong>(tableName, "id");
            SourceZoneId = new global::SpacetimeDB.Col<Portal, ulong>(tableName, "source_zone_id");
            DestZoneId = new global::SpacetimeDB.Col<Portal, ulong>(tableName, "dest_zone_id");
            SourceX = new global::SpacetimeDB.Col<Portal, float>(tableName, "source_x");
            SourceY = new global::SpacetimeDB.Col<Portal, float>(tableName, "source_y");
            DestSpawnX = new global::SpacetimeDB.Col<Portal, float>(tableName, "dest_spawn_x");
            DestSpawnY = new global::SpacetimeDB.Col<Portal, float>(tableName, "dest_spawn_y");
            Bidirectional = new global::SpacetimeDB.Col<Portal, bool>(tableName, "bidirectional");
            Label = new global::SpacetimeDB.Col<Portal, string>(tableName, "label");
        }
    }

    public sealed class PortalIxCols
    {
        public global::SpacetimeDB.IxCol<Portal, ulong> Id { get; }
        public global::SpacetimeDB.IxCol<Portal, ulong> SourceZoneId { get; }
        public global::SpacetimeDB.IxCol<Portal, ulong> DestZoneId { get; }

        public PortalIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<Portal, ulong>(tableName, "id");
            SourceZoneId = new global::SpacetimeDB.IxCol<Portal, ulong>(tableName, "source_zone_id");
            DestZoneId = new global::SpacetimeDB.IxCol<Portal, ulong>(tableName, "dest_zone_id");
        }
    }
}
