// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class SpawnPointHandle : RemoteTableHandle<EventContext, SpawnPoint>
        {
            protected override string RemoteTableName => "spawn_point";

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(SpawnPoint row) => row.Id;

                public IdUniqueIndex(SpawnPointHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            public sealed class ZoneIdIndex : BTreeIndexBase<ulong>
            {
                protected override ulong GetKey(SpawnPoint row) => row.ZoneId;

                public ZoneIdIndex(SpawnPointHandle table) : base(table) { }
            }

            public readonly ZoneIdIndex ZoneId;

            internal SpawnPointHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
                ZoneId = new(this);
            }

            protected override object GetPrimaryKey(SpawnPoint row) => row.Id;
        }

        public readonly SpawnPointHandle SpawnPoint;
    }

    public sealed class SpawnPointCols
    {
        public global::SpacetimeDB.Col<SpawnPoint, ulong> Id { get; }
        public global::SpacetimeDB.Col<SpawnPoint, ulong> ZoneId { get; }
        public global::SpacetimeDB.Col<SpawnPoint, float> X { get; }
        public global::SpacetimeDB.Col<SpawnPoint, float> Y { get; }
        public global::SpacetimeDB.Col<SpawnPoint, ulong> EnemyDefId { get; }
        public global::SpacetimeDB.Col<SpawnPoint, uint> MaxCount { get; }
        public global::SpacetimeDB.Col<SpawnPoint, uint> RespawnDelayS { get; }

        public SpawnPointCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<SpawnPoint, ulong>(tableName, "id");
            ZoneId = new global::SpacetimeDB.Col<SpawnPoint, ulong>(tableName, "zone_id");
            X = new global::SpacetimeDB.Col<SpawnPoint, float>(tableName, "x");
            Y = new global::SpacetimeDB.Col<SpawnPoint, float>(tableName, "y");
            EnemyDefId = new global::SpacetimeDB.Col<SpawnPoint, ulong>(tableName, "enemy_def_id");
            MaxCount = new global::SpacetimeDB.Col<SpawnPoint, uint>(tableName, "max_count");
            RespawnDelayS = new global::SpacetimeDB.Col<SpawnPoint, uint>(tableName, "respawn_delay_s");
        }
    }

    public sealed class SpawnPointIxCols
    {
        public global::SpacetimeDB.IxCol<SpawnPoint, ulong> Id { get; }
        public global::SpacetimeDB.IxCol<SpawnPoint, ulong> ZoneId { get; }

        public SpawnPointIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<SpawnPoint, ulong>(tableName, "id");
            ZoneId = new global::SpacetimeDB.IxCol<SpawnPoint, ulong>(tableName, "zone_id");
        }
    }
}
