// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class StatusEffectHandle : RemoteTableHandle<EventContext, StatusEffect>
        {
            protected override string RemoteTableName => "status_effect";

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(StatusEffect row) => row.Id;

                public IdUniqueIndex(StatusEffectHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            public sealed class TargetIdIndex : BTreeIndexBase<ulong>
            {
                protected override ulong GetKey(StatusEffect row) => row.TargetId;

                public TargetIdIndex(StatusEffectHandle table) : base(table) { }
            }

            public readonly TargetIdIndex TargetId;

            internal StatusEffectHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
                TargetId = new(this);
            }

            protected override object GetPrimaryKey(StatusEffect row) => row.Id;
        }

        public readonly StatusEffectHandle StatusEffect;
    }

    public sealed class StatusEffectCols
    {
        public global::SpacetimeDB.Col<StatusEffect, ulong> Id { get; }
        public global::SpacetimeDB.Col<StatusEffect, ulong> TargetId { get; }
        public global::SpacetimeDB.Col<StatusEffect, StatusEffectType> EffectType { get; }
        public global::SpacetimeDB.Col<StatusEffect, SpacetimeDB.Timestamp> ExpiresAt { get; }
        public global::SpacetimeDB.Col<StatusEffect, int> DamagePerTick { get; }

        public StatusEffectCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<StatusEffect, ulong>(tableName, "id");
            TargetId = new global::SpacetimeDB.Col<StatusEffect, ulong>(tableName, "target_id");
            EffectType = new global::SpacetimeDB.Col<StatusEffect, StatusEffectType>(tableName, "effect_type");
            ExpiresAt = new global::SpacetimeDB.Col<StatusEffect, SpacetimeDB.Timestamp>(tableName, "expires_at");
            DamagePerTick = new global::SpacetimeDB.Col<StatusEffect, int>(tableName, "damage_per_tick");
        }
    }

    public sealed class StatusEffectIxCols
    {
        public global::SpacetimeDB.IxCol<StatusEffect, ulong> Id { get; }
        public global::SpacetimeDB.IxCol<StatusEffect, ulong> TargetId { get; }

        public StatusEffectIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<StatusEffect, ulong>(tableName, "id");
            TargetId = new global::SpacetimeDB.IxCol<StatusEffect, ulong>(tableName, "target_id");
        }
    }
}
