// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class TerrainChunkHandle : RemoteTableHandle<EventContext, TerrainChunk>
        {
            protected override string RemoteTableName => "terrain_chunk";

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(TerrainChunk row) => row.Id;

                public IdUniqueIndex(TerrainChunkHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            public sealed class ZoneIdIndex : BTreeIndexBase<ulong>
            {
                protected override ulong GetKey(TerrainChunk row) => row.ZoneId;

                public ZoneIdIndex(TerrainChunkHandle table) : base(table) { }
            }

            public readonly ZoneIdIndex ZoneId;

            internal TerrainChunkHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
                ZoneId = new(this);
            }

            protected override object GetPrimaryKey(TerrainChunk row) => row.Id;
        }

        public readonly TerrainChunkHandle TerrainChunk;
    }

    public sealed class TerrainChunkCols
    {
        public global::SpacetimeDB.Col<TerrainChunk, ulong> Id { get; }
        public global::SpacetimeDB.Col<TerrainChunk, ulong> ZoneId { get; }
        public global::SpacetimeDB.Col<TerrainChunk, uint> ChunkX { get; }
        public global::SpacetimeDB.Col<TerrainChunk, uint> ChunkZ { get; }
        public global::SpacetimeDB.Col<TerrainChunk, System.Collections.Generic.List<byte>> HeightData { get; }
        public global::SpacetimeDB.Col<TerrainChunk, System.Collections.Generic.List<byte>> SplatData { get; }

        public TerrainChunkCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<TerrainChunk, ulong>(tableName, "id");
            ZoneId = new global::SpacetimeDB.Col<TerrainChunk, ulong>(tableName, "zone_id");
            ChunkX = new global::SpacetimeDB.Col<TerrainChunk, uint>(tableName, "chunk_x");
            ChunkZ = new global::SpacetimeDB.Col<TerrainChunk, uint>(tableName, "chunk_z");
            HeightData = new global::SpacetimeDB.Col<TerrainChunk, System.Collections.Generic.List<byte>>(tableName, "height_data");
            SplatData = new global::SpacetimeDB.Col<TerrainChunk, System.Collections.Generic.List<byte>>(tableName, "splat_data");
        }
    }

    public sealed class TerrainChunkIxCols
    {
        public global::SpacetimeDB.IxCol<TerrainChunk, ulong> Id { get; }
        public global::SpacetimeDB.IxCol<TerrainChunk, ulong> ZoneId { get; }

        public TerrainChunkIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<TerrainChunk, ulong>(tableName, "id");
            ZoneId = new global::SpacetimeDB.IxCol<TerrainChunk, ulong>(tableName, "zone_id");
        }
    }
}
