// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class WeatherStateHandle : RemoteTableHandle<EventContext, WeatherState>
        {
            protected override string RemoteTableName => "weather_state";

            public sealed class ZoneIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(WeatherState row) => row.ZoneId;

                public ZoneIdUniqueIndex(WeatherStateHandle table) : base(table) { }
            }

            public readonly ZoneIdUniqueIndex ZoneId;

            internal WeatherStateHandle(DbConnection conn) : base(conn)
            {
                ZoneId = new(this);
            }

            protected override object GetPrimaryKey(WeatherState row) => row.ZoneId;
        }

        public readonly WeatherStateHandle WeatherState;
    }

    public sealed class WeatherStateCols
    {
        public global::SpacetimeDB.Col<WeatherState, ulong> ZoneId { get; }
        public global::SpacetimeDB.Col<WeatherState, WeatherKind> Kind { get; }
        public global::SpacetimeDB.Col<WeatherState, float> Intensity { get; }
        public global::SpacetimeDB.Col<WeatherState, SpacetimeDB.Timestamp> StartedAt { get; }

        public WeatherStateCols(string tableName)
        {
            ZoneId = new global::SpacetimeDB.Col<WeatherState, ulong>(tableName, "zone_id");
            Kind = new global::SpacetimeDB.Col<WeatherState, WeatherKind>(tableName, "kind");
            Intensity = new global::SpacetimeDB.Col<WeatherState, float>(tableName, "intensity");
            StartedAt = new global::SpacetimeDB.Col<WeatherState, SpacetimeDB.Timestamp>(tableName, "started_at");
        }
    }

    public sealed class WeatherStateIxCols
    {
        public global::SpacetimeDB.IxCol<WeatherState, ulong> ZoneId { get; }

        public WeatherStateIxCols(string tableName)
        {
            ZoneId = new global::SpacetimeDB.IxCol<WeatherState, ulong>(tableName, "zone_id");
        }
    }
}
