// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class WorldClockHandle : RemoteTableHandle<EventContext, WorldClock>
        {
            protected override string RemoteTableName => "world_clock";

            public sealed class IdUniqueIndex : UniqueIndexBase<byte>
            {
                protected override byte GetKey(WorldClock row) => row.Id;

                public IdUniqueIndex(WorldClockHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal WorldClockHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(WorldClock row) => row.Id;
        }

        public readonly WorldClockHandle WorldClock;
    }

    public sealed class WorldClockCols
    {
        public global::SpacetimeDB.Col<WorldClock, byte> Id { get; }
        public global::SpacetimeDB.Col<WorldClock, ushort> MinutesOfDay { get; }
        public global::SpacetimeDB.Col<WorldClock, SpacetimeDB.Timestamp> LastTick { get; }

        public WorldClockCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<WorldClock, byte>(tableName, "id");
            MinutesOfDay = new global::SpacetimeDB.Col<WorldClock, ushort>(tableName, "minutes_of_day");
            LastTick = new global::SpacetimeDB.Col<WorldClock, SpacetimeDB.Timestamp>(tableName, "last_tick");
        }
    }

    public sealed class WorldClockIxCols
    {
        public global::SpacetimeDB.IxCol<WorldClock, byte> Id { get; }

        public WorldClockIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<WorldClock, byte>(tableName, "id");
        }
    }
}
