// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class ZoneHandle : RemoteTableHandle<EventContext, Zone>
        {
            protected override string RemoteTableName => "zone";

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(Zone row) => row.Id;

                public IdUniqueIndex(ZoneHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal ZoneHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(Zone row) => row.Id;
        }

        public readonly ZoneHandle Zone;
    }

    public sealed class ZoneCols
    {
        public global::SpacetimeDB.Col<Zone, ulong> Id { get; }
        public global::SpacetimeDB.Col<Zone, string> Name { get; }
        public global::SpacetimeDB.Col<Zone, uint> TerrainWidth { get; }
        public global::SpacetimeDB.Col<Zone, uint> TerrainHeight { get; }
        public global::SpacetimeDB.Col<Zone, float> WaterLevel { get; }

        public ZoneCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<Zone, ulong>(tableName, "id");
            Name = new global::SpacetimeDB.Col<Zone, string>(tableName, "name");
            TerrainWidth = new global::SpacetimeDB.Col<Zone, uint>(tableName, "terrain_width");
            TerrainHeight = new global::SpacetimeDB.Col<Zone, uint>(tableName, "terrain_height");
            WaterLevel = new global::SpacetimeDB.Col<Zone, float>(tableName, "water_level");
        }
    }

    public sealed class ZoneIxCols
    {
        public global::SpacetimeDB.IxCol<Zone, ulong> Id { get; }

        public ZoneIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<Zone, ulong>(tableName, "id");
        }
    }
}
